---
- name: Install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ zsh_dependencies }}"
  tags: packages

- name: Get zsh path
  command: which zsh 
  register: zsh_path
  changed_when: no
  tags: configuration

- name: Switch to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes 
  tags: configuration

- name: Clone oh-my-zsh repository
  become: yes
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    accept_hostkey: yes
    update: no
  tags: configuration


- name: Clone oh-my-zsh custom plugin
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    accept_hostkey: yes
    update: no
  with_items: "{{ zsh_ohmy_custom_plugins }}"
  tags: configuration


- name: Set permissions for oh my zsh dir
  become: yes
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: directory
    recurse: yes
  tags: configuration

- name: Create zsh config file
  become: yes
  template:
    src: zsh.config.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0640
  tags: configuration
